import Head from "next/head";
import Image from "next/image";

import { userContext, UserContextProvider } from "../components/UserContext";
import { Route, BrowserRouter as Router, Routes } from "react-router-dom";
import Navbar from "../components/Navbar";
import Main from "../components/Main";
import Icons from "../components/Icons";
import Section2 from "../components/Section2";
import Founders from "../components/Founders";

export default function Home() {
    return (
        <>
            <Head>
                <title>Dev House</title>

                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />

                <link rel="icon" href="/favicon.ico" />

                <script
                    src="https://kit.fontawesome.com/1beabbb46f.js"
                    crossorigin="anonymous"
                ></script>
            </Head>
            <div>
                <UserContextProvider>
                    <Navbar />
              
                    <Main />
                    <Icons />
                    <Section2/>
                    <Founders/>
                </UserContextProvider>
            </div>
        </>
    );
}
